-- 유저 데이터 2행 삽입
INSERT ALL 
    INTO SYS_SYSTEM_CODE_DATA_KHM
    (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5)
    VALUES ('MealPlan', 'Users', 'user1', 1, 'pwd1234', '김사랑', '990514','남자','177','93')
    INTO SYS_SYSTEM_CODE_DATA_KHM
    (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5)
    VALUES ('MealPlan', 'Users', 'user2', 2, 'pwd1234', '문종훈', '000514','여자','180','75')
    SELECT * FROM DUAL;

-- 음식 데이터 100행 삽입
INSERT ALL
    INTO SYS_SYSTEM_CODE_DATA_KHM
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20001',1,'제육덮밥','779','115','29','21','1','인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20002', 2,'사과','61','16','0','0','1','개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20003',3,'콩나물무침','48','7','2','1','100','g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20004', 4, '김치찌개', '284', '14', '20', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20005', 5, '불고기', '335', '18', '24', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20006', 6, '비빔밥', '560', '80', '18', '14', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20007', 7, '된장찌개', '170', '12', '10', '9', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20008', 8, '삼겹살', '510', '0', '21', '47', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20009', 9, '김밥', '360', '60', '10', '9', '1', '줄')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20010', 10, '떡볶이', '400', '70', '10', '9', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20011', 11, '라면', '500', '70', '10', '18', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20012', 12, '잡채', '280', '40', '10', '9', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20013', 13, '닭강정', '540', '60', '20', '25', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20014', 14, '오징어볶음', '220', '12', '18', '9', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20015', 15, '계란찜', '150', '2', '10', '12', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20016', 16, '미역국', '90', '4', '5', '3', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20017', 17, '김치전', '320', '40', '10', '14', '1', '장')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20018', 18, '두부조림', '140', '8', '10', '6', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20019', 19, '우유', '130', '10', '8', '6', '200', 'ml')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20020', 20, '샐러드', '90', '10', '3', '4', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20021', 21, '부대찌개', '530', '28', '25', '30', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20022', 22, '순두부찌개', '250', '12', '18', '15', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20023', 23, '오므라이스', '620', '80', '20', '20', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20024', 24, '돈까스', '750', '55', '30', '40', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20025', 25, '감자조림', '150', '20', '2', '6', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20026', 26, '멸치볶음', '180', '5', '15', '10', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20027', 27, '깍두기', '40', '9', '1', '0', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20028', 28, '콩자반', '230', '20', '10', '10', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20029', 29, '카레라이스', '670', '90', '20', '20', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20030', 30, '도시락김', '25', '1', '1', '2', '1', '봉지')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20031', 31, '계란후라이', '90', '1', '6', '7', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20032', 32, '닭가슴살', '165', '0', '31', '4', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20033', 33, '우동', '520', '70', '12', '15', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20034', 34, '냉면', '430', '70', '10', '8', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20035', 35, '갈비찜', '780', '25', '35', '50', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20036', 36, '감자탕', '550', '20', '30', '35', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20037', 37, '누룽지', '180', '38', '3', '1', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20038', 38, '참치김밥', '400', '60', '15', '10', '1', '줄')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20039', 39, '순대', '450', '35', '12', '30', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20040', 40, '떡국', '520', '60', '15', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20041', 41, '김치볶음밥', '540', '65', '12', '20', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM   
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20042', 42, '해물파전', '480', '40', '15', '25', '1', '장')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20043', 43, '갈비탕', '460', '10', '30', '30', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20044', 44, '소고기미역국', '210', '5', '18', '12', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20045', 45, '오징어채볶음', '200', '15', '12', '8', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20046', 46, '고등어구이', '320', '0', '25', '24', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20047', 47, '코다리조림', '280', '12', '25', '10', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20048', 48, '콩비지찌개', '290', '10', '20', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20049', 49, '닭볶음탕', '680', '25', '35', '40', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20050', 50, '애호박볶음', '120', '6', '3', '7', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20051', 51, '오이무침', '80', '5', '2', '5', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20052', 52, '북어국', '150', '3', '15', '7', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20053', 53, '감자전', '360', '50', '4', '15', '1', '장')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20054', 54, '계란말이', '240', '2', '12', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20055', 55, '양배추쌈', '50', '9', '2', '0', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20056', 56, '호박죽', '280', '60', '3', '2', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20057', 57, '찐만두', '480', '50', '15', '20', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20058', 58, '쫄면', '620', '90', '12', '20', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20059', 59, '스팸구이', '410', '3', '12', '40', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20060', 60, '떡꼬치', '300', '40', '6', '12', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20061', 61, '쌈장', '120', '8', '2', '9', '30', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20062', 62, '양념치킨', '950', '60', '40', '60', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20063', 63, '치즈돈까스', '890', '50', '35', '55', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20064', 64, '카스테라', '320', '45', '5', '15', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20065', 65, '단무지', '25', '6', '0', '0', '50', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20066', 66, '식빵', '240', '45', '6', '3', '2', '쪽')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20067', 67, '된장국', '95', '6', '5', '4', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20068', 68, '청국장', '180', '9', '14', '10', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20069', 69, '고추장불고기', '550', '35', '28', '32', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20070', 70, '유부초밥', '380', '60', '8', '10', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20071', 71, '메추리알조림', '230', '8', '12', '14', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20072', 72, '잡곡밥', '310', '60', '6', '2', '1', '공기')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20073', 73, '주먹밥', '420', '70', '10', '8', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20074', 74, '소시지볶음', '400', '20', '15', '30', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20075', 75, '어묵탕', '180', '15', '10', '8', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20076', 76, '콩나물국', '90', '6', '5', '3', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20077', 77, '깻잎장아찌', '70', '3', '2', '6', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20078', 78, '돼지불백', '650', '30', '28', '35', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20079', 79, '도토리묵', '140', '15', '2', '6', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20080', 80, '참치마요덮밥', '620', '70', '18', '25', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20081', 81, '마카로니샐러드', '320', '40', '6', '15', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20082', 82, '크림스파게티', '650', '70', '15', '35', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20083', 83, '토스트', '280', '35', '8', '12', '1', '쪽')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20084', 84, '핫도그', '410', '45', '10', '20', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20085', 85, '군고구마', '150', '35', '2', '0', '100', 'g')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20086', 86, '찐옥수수', '140', '30', '4', '1', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20087', 87, '계란샌드위치', '350', '40', '12', '15', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20088', 88, '햄버거', '700', '60', '25', '35', '1', '개')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20089', 89, '치킨너겟', '450', '25', '15', '30', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20090', 90, '볶음우동', '580', '70', '14', '25', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20091', 91, '카레우동', '600', '85', '12', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20092', 92, '간장계란밥', '400', '50', '10', '12', '1', '공기')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20093', 93, '어묵볶음', '210', '10', '10', '12', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20094', 94, '브로콜리나물', '70', '5', '4', '3', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20095', 95, '두부샐러드', '200', '8', '15', '10', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20096', 96, '버섯볶음', '120', '6', '5', '7', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20097', 97, '미니돈까스', '520', '35', '20', '30', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20098', 98, '소고기장조림', '310', '5', '28', '18', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20099', 99, '연근조림', '150', '20', '2', '6', '1', '인분')
    INTO SYS_SYSTEM_CODE_DATA_KHM 
        (PLANT, TABLE_NAME, CODE_NAME, CODE_SEQ, DESCRIPTION, CODE_GROUP1, CODE_GROUP2, CODE_GROUP3, CODE_GROUP4,CODE_GROUP5,EXP_DESCRIPTION)
        VALUES ('MealPlan', 'Foods', '20100', 100, '꽈리고추볶음', '130', '8', '3', '8', '1', '인분')
SELECT * FROM DUAL;


-- 식단 데이터 삽입

INSERT ALL
    INTO SYS_SYSTEM_CODE_DATA_KHM 
    VALUES('MealPlan','Meals', '10001',1, 'user1', '아침',to_date(sysdate,'yy/mm/dd'),null,null,null,null,null,null,null,null,null)
    INTO SYS_SYSTEM_CODE_DATA_KHM 
    VALUES('MealPlan','Meals', '10002',2, 'user1', '점심',to_date(sysdate,'yy/mm/dd'),null,null,null,null,null,null,null,null,null)
    INTO SYS_SYSTEM_CODE_DATA_KHM 
    VALUES('MealPlan','Meals', '10004',4, 'user1', '아침',to_date('2025/08/03','yy/mm/dd'),null,null,null,null,null,null,null,null,null)
    INTO SYS_SYSTEM_CODE_DATA_KHM 
    VALUES('MealPlan','Meals', '10005',5, 'user1', '점심',to_date('2025/08/03','yy/mm/dd'),null,null,null,null,null,null,null,null,null)
SELECT * FROM DUAL;

-- 식단_음식 데이터 삽입.
INSERT ALL
    INTO SYS_SYSTEM_CODE_DATA_KHM
    VALUES('MealPlan','Meal_Foods','30001',1,'10001','20001',1,null,null,null,null,null,null,null,null,null)
    INTO SYS_SYSTEM_CODE_DATA_KHM
    VALUES('MealPlan','Meal_Foods','30002',2,'10001','20002',1,null,null,null,null,null,null,null,null,null)
    INTO SYS_SYSTEM_CODE_DATA_KHM
    VALUES('MealPlan','Meal_Foods','30003',3,'10001','20019',100,null,null,null,null,null,null,null,null,null)
SELECT * FROM DUAL;


COMMIT;